// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmf16FTyZEJXRSzl2n6vP4eXpNmFVSzEA',
    appId: '1:34542343698:web:44ada0ae91d42de4a02acb',
    messagingSenderId: '34542343698',
    projectId: 'roots-farm-abf39',
    authDomain: 'roots-farm-abf39.firebaseapp.com',
    storageBucket: 'roots-farm-abf39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HFkA5ixNWvRlS3ihnouyJyhV6Ny2Gf4',
    appId: '1:34542343698:android:16300abab5a7010ca02acb',
    messagingSenderId: '34542343698',
    projectId: 'roots-farm-abf39',
    storageBucket: 'roots-farm-abf39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfxfZ7_vJVyZWlres1efkSS2prB48_Y0',
    appId: '1:34542343698:ios:f3a168493c41ab0fa02acb',
    messagingSenderId: '34542343698',
    projectId: 'roots-farm-abf39',
    storageBucket: 'roots-farm-abf39.firebasestorage.app',
    iosBundleId: 'com.roots.roots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkfxfZ7_vJVyZWlres1efkSS2prB48_Y0',
    appId: '1:34542343698:ios:f3a168493c41ab0fa02acb',
    messagingSenderId: '34542343698',
    projectId: 'roots-farm-abf39',
    storageBucket: 'roots-farm-abf39.firebasestorage.app',
    iosBundleId: 'com.roots.roots',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmf16FTyZEJXRSzl2n6vP4eXpNmFVSzEA',
    appId: '1:34542343698:web:1fdc3882f4bfb7d7a02acb',
    messagingSenderId: '34542343698',
    projectId: 'roots-farm-abf39',
    authDomain: 'roots-farm-abf39.firebaseapp.com',
    storageBucket: 'roots-farm-abf39.firebasestorage.app',
  );
}
